const express = require("express");
const { json } = require("express");
const cors = require("cors");

const app = express();
app.use(json());
app.use(cors());

app.get("/", (req, res) => {
  res.send("Hiiii");
});

app.get("/fetch", (req, res) => {
  data = {
    id: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
    name: "flutter-api Copy",
    description: "",
    order: [
      "60400283-2351-7adc-624c-cdd644efaddc",
      "67ae0a9c-3033-e6fd-9704-00f7548f32e0",
      "25b24c08-c5be-bd62-91ad-357675b2476d",
      "2c00c6cc-7be7-3e01-92b8-c10c52628de7",
      "b2d17037-eeb2-0d30-4b53-50753524f417",
      "98bd06a4-e672-ec16-69ac-83c37a73acb2",
      "d032cb6b-e2e2-c115-e9cd-75058442fc6b",
      "794c6f2f-c2db-d834-5637-f8d48366226c",
      "d6e75c27-5e29-ce48-58d0-a7dc9f70172b",
      "2817ede9-0d7d-1990-a5e6-b6cab8bab55a",
    ],
    folders_order: [],
    folders: [],
    owner: 0,
    hasRequests: true,
    requests: [
      {
        id: "25b24c08-c5be-bd62-91ad-357675b2476d",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/getUserProfile",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "GET",
        data: [],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762627065,
        name: "user-profile",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "2817ede9-0d7d-1990-a5e6-b6cab8bab55a",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/products?page=1",
        queryParams: [
          {
            key: "page",
            value: "1",
            equals: true,
            description: "",
            enabled: true,
          },
        ],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "GET",
        data: [],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762670001,
        name: "pagination",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "2c00c6cc-7be7-3e01-92b8-c10c52628de7",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/products",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "POST",
        data: [
          {
            key: "name",
            value: "mobile",
            type: "text",
          },
          {
            key: "mrp",
            value: "23600",
            type: "text",
          },
          {
            key: "selling",
            value: "2",
            type: "text",
          },
          {
            key: "description",
            value: "uyjuyju",
            type: "text",
          },
          {
            key: "image",
            type: "file",
            src: "/home/planet/Downloads/img/photo-1610878180933-123728745d22.jpeg",
            value: "",
          },
        ],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762633073,
        name: "product-add",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "60400283-2351-7adc-624c-cdd644efaddc",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/register",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "POST",
        data: [
          {
            key: "name",
            value: "demo",
            type: "text",
          },
          {
            key: "email",
            value: "fgf12g@gmail.com",
            type: "text",
          },
          {
            key: "password",
            value: "12345678",
            type: "text",
          },
          {
            key: "image",
            type: "file",
            src: "/home/planet/Pictures/3d-waterfall-nature-wallpaper-500x500.jpg",
            value: "",
          },
          {
            key: "password_confirmation",
            value: "1234567",
            type: "text",
          },
        ],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762612241,
        name: "register",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "67ae0a9c-3033-e6fd-9704-00f7548f32e0",
        headers: "Content-Type: application/x-www-form-urlencoded\n",
        headerData: [
          {
            key: "Content-Type",
            value: "application/x-www-form-urlencoded",
            description: "",
            enabled: true,
          },
        ],
        url: "https://dignizant.com/flutter-api/public/api/login",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "POST",
        data: [
          {
            key: "email",
            value: "pkl@gmail.com",
            type: "text",
            enabled: true,
            description: "",
          },
          {
            key: "password",
            value: "12345678",
            type: "text",
            enabled: true,
            description: "",
          },
        ],
        dataMode: "urlencoded",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762595785,
        name: "login",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "794c6f2f-c2db-d834-5637-f8d48366226c",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/products/5",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "DELETE",
        data: [],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762654065,
        name: "product-delete",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "98bd06a4-e672-ec16-69ac-83c37a73acb2",
        headers: "//Content-Type: multipart/form-data\n",
        headerData: [
          {
            key: "Content-Type",
            value: "multipart/form-data",
            description: "",
            enabled: false,
          },
        ],
        url: "https://dignizant.com/flutter-api/public/api/products/7",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "PUT",
        data: [
          {
            key: "name",
            value: "testing",
            type: "text",
          },
          {
            key: "mrp",
            value: "2522",
            type: "text",
          },
          {
            key: "selling",
            value: "200",
            type: "text",
          },
          {
            key: "description",
            value: "uyjuyjubcb",
            type: "text",
          },
          {
            key: "_method",
            value: "PUT",
            type: "text",
          },
        ],
        dataMode: "urlencoded",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762644993,
        name: "products-update",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "b2d17037-eeb2-0d30-4b53-50753524f417",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/products",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "GET",
        data: [],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762639025,
        name: "list-product",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "d032cb6b-e2e2-c115-e9cd-75058442fc6b",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/products/3",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "GET",
        data: [],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762649537,
        name: "show-product",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
      {
        id: "d6e75c27-5e29-ce48-58d0-a7dc9f70172b",
        headers: "",
        headerData: [],
        url: "https://dignizant.com/flutter-api/public/api/profileUpdate/27",
        queryParams: [],
        preRequestScript: null,
        pathVariables: {},
        pathVariableData: [],
        method: "POST",
        data: [
          {
            key: "name",
            value: "demo",
            type: "text",
          },
          {
            key: "email",
            value: "pkl@gmail.com",
            type: "text",
          },
          {
            key: "_method",
            value: "PUT",
            type: "text",
          },
        ],
        dataMode: "params",
        tests: null,
        currentHelper: "normal",
        helperAttributes: {},
        time: 1663762658681,
        name: "profileUpdate",
        description: "",
        collectionId: "eaafed71-4464-24a7-36d4-06b3c2fe15cf",
        responses: [],
      },
    ],
  };
  res.send(data);
});

const server = app.listen(5000, (req, res) => {
  console.log("server is running - 5000 ");
});
